### ISSUE TITLE
Unable to install angular cli using `ngvm install -g`

### ISSUE THREAD

**Issue by itsmehrd** [angularconsulting/ngvm#3]
I am unable to see any progress on `ngvm install` or `ngvm install 17` or `ngvm install -g`
![image](https://github.com/angularconsulting/ngvm/assets/83162647/486cf46f-c208-481b-b944-551489e64155)
```
ngvm -v
0.0.7
```
I am running node using `nvm`
```
nvm version
1.1.12
```
and the node version is given below
```
node -v
v20.10.0
```

**Comment by kuncevic** [comment]
Hey @itsmehrd this could be a platform (Windows) specific issue related to nvm, npm or node. Unfortunately I can't replicate that having different environment.

**Comment by YandyZaldivar** [comment]
Same, `ngvm install -g` does nothing.

Tested on win11-pro with nvm installed using node 16 lts.

It should be possible to replicate this on a clean win vm.

**Comment by kuncevic** [comment]
@YandyZaldivar would you mind grinning that same command with `--debug` flag `ngvm install -g --debug` and paste an output ?

**Comment by kuncevic** [comment]
@YandyZaldivar would you mind running that same command with `--debug` flag `ngvm install -g --debug` and paste an output ?
